apiVersion: v1
kind: Pod
metadata:
  name: discovery
  labels:
    name: discovery
spec:  
  containers:
  - name: discovery
    image: "localhost:5000/elipcero/discoveryservice:latest"
    ports:
      - containerPort: 8761
