apiVersion: v1
kind: ReplicationController
metadata:
  name: orderline
  labels:
    name: orderline
spec:
  replicas: 1
  selector:
    name: orderline
  template:
    metadata:
      labels:
        name: orderline
    spec:
      containers:
      - name: orderline
        image: "localhost:5000/elipcero/orderlineservice"
        ports:
            - containerPort: 8080
